[project]
name = "nekt-sdk"
version = "0.2.7"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "delta-spark==3.3.0",
    "pyspark==3.5.5",
    "requests>=2.32.3",
]
